[package]
name = "ngx-strict-sni"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
ngx = { git = "https://github.com/JyJyJcr/ngx-rust",branch="ngx_install_dir" }
