[package]
name = "ngx-strict-sni"
version = "1.0.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
name = "ngx_http_ssl_strict_sni"

[dependencies]
ngx = { git = "https://github.com/JyJyJcr/ngx-rust",branch="ngx_install_dir" }
