[env]
# ZLIB_VERSION = "1.3.1"
# PCRE2_VERSION = "10.42"
# OPENSSL_VERSION = "3.2.1"
NGX_VERSION = "1.22.1"
NGX_INSTALL_ROOT_DIR = { value = ".nginx", relative = true }
CACHE_DIR = { value = ".cache", relative = true }

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
