name: compile action test

on: push

jobs:
  compile:
    name: "compile test"
    strategy:
      fail-fast: true
      matrix:
        platform:
          - target: "aarch64-unknown-linux-gnu"
            host: "ubuntu-latest"
    runs-on: ${{matrix.platform.host}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          args: "--locked"
          strip: true
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ matrix.platform.target }}
          path: "target/${{ matrix.platform.target }}/debug/*ngx_http_ssl_strict_sni.*"
