name: compile action test

on: push

jobs:
  compile:
    name: "compile test"
    strategy:
      #fail-fast: true
      matrix:
        platform:
          - target: "aarch64-unknown-linux-gnu"
            host: "ubuntu-latest"
          - target: "x86_64-unknown-linux-gnu"
            host: "ubuntu-latest"
          - target: "aarch64-apple-darwin"
            host: "macOS-latest"
          - target: "x86_64-apple-darwin"
            host: "macOS-latest"
    runs-on: ${{matrix.platform.host}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: toolchain
        run: rustup target install ${{ matrix.platform.target }}
      - name: build
        run: cargo build --target ${{ matrix.platform.target }}
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ matrix.platform.target }}
          path: "target/${{ matrix.platform.target }}/debug/*ngx_http_ssl_strict_sni.*"
